# Generated by Django 4.0.4 on 2023-02-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='created_date',
            field=models.DateField(),
        ),
    ]
