# Generated by Django 4.0.4 on 2023-02-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todotask_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
